<?php
// lib/email_helpers.php
// Simple helpers for generating HTML emails and sending via PHP's mail().

function generate_email_body(string $title, string $message, string $link): string {
    $msg = nl2br(htmlspecialchars($message));
    return <<<HTML
    <html>
    <head>
      <meta charset="UTF-8">
      <style type="text/css">
        body { font-family: Arial, sans-serif; color: #333; margin:0; padding:0; }
        .email-container { width:100%; max-width:600px; margin:20px auto; padding:20px; border:1px solid #ddd; background-color:#f9f9f9; }
        .header { background-color:#24549C; padding:15px; text-align:center; color:#fff; font-size:22px; }
        .content { margin:20px 0; font-size:16px; line-height:1.4; }
        .btn { display:inline-block; background-color:#24549C; color:#fff; padding:10px 20px; text-decoration:none; border-radius:5px; margin-top:15px; }
        .footer { margin-top:20px; font-size:12px; text-align:center; color:#888; }
      </style>
    </head>
    <body>
      <div class="email-container">
        <div class="header">{$title}</div>
        <div class="content">
          <p>{$msg}</p>
          <p style="text-align:center;"><a class="btn" href="{$link}">View Schedule</a></p>
        </div>
        <div class="footer"><p>This email was automatically generated by Armstrong Scheduler.</p></div>
      </div>
    </body>
    </html>
HTML;
}

function send_email(array $toEmails, string $subject, string $body, array $ccEmails = []): void {
    $to       = implode(',', $toEmails);
    $headers  = "MIME-Version: 1.0\r\n";
    $headers .= "Content-type: text/html; charset=UTF-8\r\n";
    if ($ccEmails) {
        $headers .= 'Cc: ' . implode(',', $ccEmails) . "\r\n";
    }
    @mail($to, $subject, $body, $headers);
}
